version: '3.0'
services:
  ocserv:
    image: flaminigo/ocserv-github
    restart: always
    container_name: ocserv-test
    privileged: true
    hostname: www.example.com
    ports:
      - 995:443/udp
      - 995:443
    volumes:
      - ocserv-config:/etc/ocserv
    environment:
      - CA_CN=VPN CA
      - CA_ORG=Big Corp
      - CA_DAYS=9999
      - SRV_CN=www.example.com
      - SRV_ORG=My Company
      - SRV_DAYS=9999

volumes:
  ocserv-config:
    driver: local
