version: '3.0'
services:

  traefik:
    image: traefik:v1.7
    restart: always
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    networks:
      default:
      vpn-share:
        ipv4_address: 172.16.238.100
    volumes:
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/dyn.toml:/etc/traefik/dyn.toml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
       - "traefik.frontend.rule=Host:monitor.localhost.com"
       - "traefik.port=8080"

  ocserv:
    image: flaminigo/ocserv-github
    restart: always
    container_name: ocserv-github
    privileged: true
    hostname: www.example.com
    ports:
      - 995:443/udp
      - 995:443
    volumes:
      - ocserv-config:/etc/ocserv
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - CA_CN=VPN CA
      - CA_ORG=Big Corp
      - CA_DAYS=9999
      - SRV_CN=www.example.com
      - SRV_ORG=My Company
      - SRV_DAYS=9999
    networks:
      vpn-share:
        ipv4_address: 172.16.238.10


  ad-blocker:
    image: oznu/dns-ad-blocker
    restart: always
    container_name: ad-blocker
    #ports:
      #- 53:53/tcp
      #- 53:53/udp
    volumes:
      - ad-blocker-config:/config
    environment:
      - NS1=1.1.1.1
      - NS2=1.0.0.1
      - AUTO_UPDATE=1
      - DNSCRYPT=1
    networks:
      vpn-share:
        ipv4_address: 172.16.238.11

  ikev2-vpn:
    image: flaminigo/ike
    restart: always
    container_name: ikev2-vpn
    privileged: true
    ports:
      - 500:500/udp
      - 4500:4500/udp
    networks:
      vpn-share:
        ipv4_address: 172.16.238.12

  radius:
    image: flaminigo/radius
    restart: always
    container_name: radius
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    networks:
      vpn-share:
        ipv4_address: 172.16.238.15
    volumes:
      - radius-cfg:/opt/etc/raddb
      - /etc/letsencrypt:/etc/letsencrypt

  music:
    image: nondanee/unblockneteasemusic
    restart: always
    container_name: music
    #ports:
    #  - 80:8080
    networks:
      vpn-share:
        ipv4_address: 172.16.238.16
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:main.localhost.com"

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=x5SkEGr3256AecJSo0Gcb747Qad
      - MYSQL_PASSWORD=x5SkEGr3256AecJSo0
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    #ports:
    #  - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      vpn-share:
        ipv4_address: 172.16.238.17
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:cloud.localhost.com"
      - "traefik.port=80"

volumes:
  ocserv-config:
    driver: local
  radius-cfg:
    driver: local
  ad-blocker-config:
    driver: local
  db:
  nextcloud:

networks:
    vpn-share:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
