version: '3.0'
services:
  ocserv:
    image: flaminigo/ocserv-github
    restart: always
    container_name: ocserv-github
    privileged: true
    hostname: www.example.com
    ports:
      - 995:443/udp
      - 995:443
    volumes:
      - ocserv-config:/etc/ocserv
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - CA_CN=VPN CA
      - CA_ORG=Big Corp
      - CA_DAYS=9999
      - SRV_CN=www.example.com
      - SRV_ORG=My Company
      - SRV_DAYS=9999
    networks:
      - vpn-share

  ad-blocker:
    image: oznu/dns-ad-blocker
    restart: always
    container_name: ad-blocker
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      - NS1=1.1.1.1
      - NS2=1.0.0.1
      - AUTO_UPDATE=1
    networks:
      - vpn-share

  ikev2-vpn:
    image: flaminigo/ike
    restart: always
    container_name: ikev2-vpn
    privileged: true
    ports:
      - 500:500/udp
      - 4500:4500/udp
    networks:
      - vpn-share

volumes:
  ocserv-config:
    driver: local

networks:
    vpn-share:
